#!/usr/bin/env python3
"""
Insertar las 346 comunas de Chile en Neon
"""
import psycopg2

COMUNAS = [
    # Arica y Parinacota (XV)
    ("Arica", "Arica y Parinacota", "XV"), ("Camarones", "Arica y Parinacota", "XV"), ("General Lagos", "Arica y Parinacota", "XV"), ("Putre", "Arica y Parinacota", "XV"),
    # Tarapacá (I)
    ("Alto Hospicio", "Tarapacá", "I"), ("Camiña", "Tarapacá", "I"), ("Colchane", "Tarapacá", "I"), ("Huara", "Tarapacá", "I"), ("Iquique", "Tarapacá", "I"), ("Pica", "Tarapacá", "I"), ("Pozo Almonte", "Tarapacá", "I"),
    # Antofagasta (II)
    ("Antofagasta", "Antofagasta", "II"), ("Calama", "Antofagasta", "II"), ("María Elena", "Antofagasta", "II"), ("Mejillones", "Antofagasta", "II"), ("Ollagüe", "Antofagasta", "II"), ("San Pedro de Atacama", "Antofagasta", "II"), ("Sierra Gorda", "Antofagasta", "II"), ("Taltal", "Antofagasta", "II"), ("Tocopilla", "Antofagasta", "II"),
    # Atacama (III)
    ("Alto del Carmen", "Atacama", "III"), ("Caldera", "Atacama", "III"), ("Chañaral", "Atacama", "III"), ("Copiapó", "Atacama", "III"), ("Diego de Almagro", "Atacama", "III"), ("Freirina", "Atacama", "III"), ("Huasco", "Atacama", "III"), ("Tierra Amarilla", "Atacama", "III"), ("Vallenar", "Atacama", "III"),
    # Coquimbo (IV)
    ("Andacollo", "Coquimbo", "IV"), ("Canela", "Coquimbo", "IV"), ("Combarbalá", "Coquimbo", "IV"), ("Coquimbo", "Coquimbo", "IV"), ("Illapel", "Coquimbo", "IV"), ("La Higuera", "Coquimbo", "IV"), ("La Serena", "Coquimbo", "IV"), ("Los Vilos", "Coquimbo", "IV"), ("Monte Patria", "Coquimbo", "IV"), ("Ovalle", "Coquimbo", "IV"), ("Paiguano", "Coquimbo", "IV"), ("Punitaqui", "Coquimbo", "IV"), ("Río Hurtado", "Coquimbo", "IV"), ("Salamanca", "Coquimbo", "IV"), ("Vicuña", "Coquimbo", "IV"),
    # Valparaíso (V)
    ("Algarrobo", "Valparaíso", "V"), ("Cabildo", "Valparaíso", "V"), ("Calle Larga", "Valparaíso", "V"), ("Cartagena", "Valparaíso", "V"), ("Casablanca", "Valparaíso", "V"), ("Catemu", "Valparaíso", "V"), ("Concón", "Valparaíso", "V"), ("El Quisco", "Valparaíso", "V"), ("El Tabo", "Valparaíso", "V"), ("Hijuelas", "Valparaíso", "V"), ("Isla de Pascua", "Valparaíso", "V"), ("Juan Fernández", "Valparaíso", "V"), ("La Calera", "Valparaíso", "V"), ("La Cruz", "Valparaíso", "V"), ("La Ligua", "Valparaíso", "V"), ("Limache", "Valparaíso", "V"), ("Llaillay", "Valparaíso", "V"), ("Los Andes", "Valparaíso", "V"), ("Nogales", "Valparaíso", "V"), ("Olmué", "Valparaíso", "V"), ("Panquehue", "Valparaíso", "V"), ("Papudo", "Valparaíso", "V"), ("Petorca", "Valparaíso", "V"), ("Puchuncaví", "Valparaíso", "V"), ("Putaendo", "Valparaíso", "V"), ("Quillota", "Valparaíso", "V"), ("Quilpué", "Valparaíso", "V"), ("Quintero", "Valparaíso", "V"), ("Rinconada", "Valparaíso", "V"), ("San Antonio", "Valparaíso", "V"), ("San Esteban", "Valparaíso", "V"), ("San Felipe", "Valparaíso", "V"), ("Santa María", "Valparaíso", "V"), ("Santo Domingo", "Valparaíso", "V"), ("Valparaíso", "Valparaíso", "V"), ("Villa Alemana", "Valparaíso", "V"), ("Viña del Mar", "Valparaíso", "V"), ("Zapallar", "Valparaíso", "V"),
    # O'Higgins (VI)
    ("Chépica", "O'Higgins", "VI"), ("Chimbarongo", "O'Higgins", "VI"), ("Codegua", "O'Higgins", "VI"), ("Coinco", "O'Higgins", "VI"), ("Coltauco", "O'Higgins", "VI"), ("Doñihue", "O'Higgins", "VI"), ("Graneros", "O'Higgins", "VI"), ("La Estrella", "O'Higgins", "VI"), ("Las Cabras", "O'Higgins", "VI"), ("Litueche", "O'Higgins", "VI"), ("Lolol", "O'Higgins", "VI"), ("Machalí", "O'Higgins", "VI"), ("Malloa", "O'Higgins", "VI"), ("Marchihue", "O'Higgins", "VI"), ("Nancagua", "O'Higgins", "VI"), ("Navidad", "O'Higgins", "VI"), ("Olivar", "O'Higgins", "VI"), ("Paredones", "O'Higgins", "VI"), ("Palmilla", "O'Higgins", "VI"), ("Peralillo", "O'Higgins", "VI"), ("Peumo", "O'Higgins", "VI"), ("Pichidegua", "O'Higgins", "VI"), ("Pichilemu", "O'Higgins", "VI"), ("Placilla", "O'Higgins", "VI"), ("Pumanque", "O'Higgins", "VI"), ("Quinta de Tilcoco", "O'Higgins", "VI"), ("Rancagua", "O'Higgins", "VI"), ("Rengo", "O'Higgins", "VI"), ("Requínoa", "O'Higgins", "VI"), ("San Fernando", "O'Higgins", "VI"), ("San Francisco de Mostazal", "O'Higgins", "VI"), ("San Vicente", "O'Higgins", "VI"), ("Santa Cruz", "O'Higgins", "VI"),
    # Maule (VII)
    ("Cauquenes", "Maule", "VII"), ("Chanco", "Maule", "VII"), ("Colbún", "Maule", "VII"), ("Constitución", "Maule", "VII"), ("Curicó", "Maule", "VII"), ("Empedrado", "Maule", "VII"), ("Hualañé", "Maule", "VII"), ("Licantén", "Maule", "VII"), ("Linares", "Maule", "VII"), ("Longaví", "Maule", "VII"), ("Maule", "Maule", "VII"), ("Molina", "Maule", "VII"), ("Parral", "Maule", "VII"), ("Pelarco", "Maule", "VII"), ("Pelluhue", "Maule", "VII"), ("Pencahue", "Maule", "VII"), ("Rauco", "Maule", "VII"), ("Retiro", "Maule", "VII"), ("Romeral", "Maule", "VII"), ("Río Claro", "Maule", "VII"), ("Sagrada Familia", "Maule", "VII"), ("San Clemente", "Maule", "VII"), ("San Javier", "Maule", "VII"), ("San Rafael", "Maule", "VII"), ("Talca", "Maule", "VII"), ("Teno", "Maule", "VII"), ("Vichuquén", "Maule", "VII"), ("Villa Alegre", "Maule", "VII"), ("Yerbas Buenas", "Maule", "VII"),
    # Ñuble (XVI)
    ("Bulnes", "Ñuble", "XVI"), ("Chillán", "Ñuble", "XVI"), ("Chillán Viejo", "Ñuble", "XVI"), ("Cobquecura", "Ñuble", "XVI"), ("Coelemu", "Ñuble", "XVI"), ("Coihueco", "Ñuble", "XVI"), ("El Carmen", "Ñuble", "XVI"), ("Ninhue", "Ñuble", "XVI"), ("Ñiquén", "Ñuble", "XVI"), ("Pemuco", "Ñuble", "XVI"), ("Pinto", "Ñuble", "XVI"), ("Portezuelo", "Ñuble", "XVI"), ("Quillón", "Ñuble", "XVI"), ("Quirihue", "Ñuble", "XVI"), ("Ránquil", "Ñuble", "XVI"), ("San Carlos", "Ñuble", "XVI"), ("San Fabián", "Ñuble", "XVI"), ("San Ignacio", "Ñuble", "XVI"), ("San Nicolás", "Ñuble", "XVI"), ("Treguaco", "Ñuble", "XVI"), ("Yungay", "Ñuble", "XVI"),
    # Biobío (VIII)
    ("Alto Biobío", "Biobío", "VIII"), ("Antuco", "Biobío", "VIII"), ("Arauco", "Biobío", "VIII"), ("Bulnes", "Biobío", "VIII"), ("Cabrero", "Biobío", "VIII"), ("Cañete", "Biobío", "VIII"), ("Chiguayante", "Biobío", "VIII"), ("Concepción", "Biobío", "VIII"), ("Contulmo", "Biobío", "VIII"), ("Coronel", "Biobío", "VIII"), ("Curanilahue", "Biobío", "VIII"), ("Florida", "Biobío", "VIII"), ("Hualpén", "Biobío", "VIII"), ("Hualqui", "Biobío", "VIII"), ("Laja", "Biobío", "VIII"), ("Lebu", "Biobío", "VIII"), ("Los Álamos", "Biobío", "VIII"), ("Los Ángeles", "Biobío", "VIII"), ("Lota", "Biobío", "VIII"), ("Mulchén", "Biobío", "VIII"), ("Nacimiento", "Biobío", "VIII"), ("Negrete", "Biobío", "VIII"), ("Penco", "Biobío", "VIII"), ("Quilaco", "Biobío", "VIII"), ("Quilleco", "Biobío", "VIII"), ("San Pedro de la Paz", "Biobío", "VIII"), ("Rosales", "Biobío", "VIII"), ("San Rosendo", "Biobío", "VIII"), ("Santa Bárbara", "Biobío", "VIII"), ("Santa Juana", "Biobío", "VIII"), ("Talcahuano", "Biobío", "VIII"), ("Tirúa", "Biobío", "VIII"), ("Tomé", "Biobío", "VIII"), ("Tucapel", "Biobío", "VIII"), ("Yumbel", "Biobío", "VIII"),
    # Araucanía (IX)
    ("Angol", "Araucanía", "IX"), ("Carahue", "Araucanía", "IX"), ("Cholchol", "Araucanía", "IX"), ("Collipulli", "Araucanía", "IX"), ("Cunco", "Araucanía", "IX"), ("Curacautín", "Araucanía", "IX"), ("Curarrehue", "Araucanía", "IX"), ("Ercilla", "Araucanía", "IX"), ("Freire", "Araucanía", "IX"), ("Galvarino", "Araucanía", "IX"), ("Gorbea", "Araucanía", "IX"), ("Lautaro", "Araucanía", "IX"), ("Loncoche", "Araucanía", "IX"), ("Lonquimay", "Araucanía", "IX"), ("Los Sauces", "Araucanía", "IX"), ("Lumaco", "Araucanía", "IX"), ("Melipeuco", "Araucanía", "IX"), ("Nueva Imperial", "Araucanía", "IX"), ("Padre Las Casas", "Araucanía", "IX"), ("Perquenco", "Araucanía", "IX"), ("Pitrufquén", "Araucanía", "IX"), ("Pucón", "Araucanía", "IX"), ("Purén", "Araucanía", "IX"), ("Renaico", "Araucanía", "IX"), ("Saavedra", "Araucanía", "IX"), ("Temuco", "Araucanía", "IX"), ("Teodoro Schmidt", "Araucanía", "IX"), ("Toltén", "Araucanía", "IX"), ("Traiguén", "Araucanía", "IX"), ("Victoria", "Araucanía", "IX"), ("Vilcún", "Araucanía", "IX"), ("Villarrica", "Araucanía", "IX"),
    # Los Ríos (XIV)
    ("Corral", "Los Ríos", "XIV"), ("Futrono", "Los Ríos", "XIV"), ("La Unión", "Los Ríos", "XIV"), ("Lago Ranco", "Los Ríos", "XIV"), ("Lanco", "Los Ríos", "XIV"), ("Los Lagos", "Los Ríos", "XIV"), ("Máfil", "Los Ríos", "XIV"), ("Mariquina", "Los Ríos", "XIV"), ("Paillaco", "Los Ríos", "XIV"), ("Panguipulli", "Los Ríos", "XIV"), ("Río Bueno", "Los Ríos", "XIV"), ("San José de la Mariquina", "Los Ríos", "XIV"), ("Valdivia", "Los Ríos", "XIV"),
    # Los Lagos (X)
    ("Ancud", "Los Lagos", "X"), ("Calbuco", "Los Lagos", "X"), ("Castro", "Los Lagos", "X"), ("Chaitén", "Los Lagos", "X"), ("Chonchi", "Los Lagos", "X"), ("Cochamó", "Los Lagos", "X"), ("Curaco de Vélez", "Los Lagos", "X"), ("Dalcahue", "Los Lagos", "X"), ("Fresia", "Los Lagos", "X"), ("Frutillar", "Los Lagos", "X"), ("Futaleufú", "Los Lagos", "X"), ("Hualaihué", "Los Lagos", "X"), ("Llanquihue", "Los Lagos", "X"), ("Los Muermos", "Los Lagos", "X"), ("Maullín", "Los Lagos", "X"), ("Osorno", "Los Lagos", "X"), ("Palena", "Los Lagos", "X"), ("Puerto Montt", "Los Lagos", "X"), ("Puerto Octay", "Los Lagos", "X"), ("Puerto Varas", "Los Lagos", "X"), ("Puqueldón", "Los Lagos", "X"), ("Purranque", "Los Lagos", "X"), ("Puyehue", "Los Lagos", "X"), ("Queilén", "Los Lagos", "X"), ("Quellón", "Los Lagos", "X"), ("Quemchi", "Los Lagos", "X"), ("Quinchao", "Los Lagos", "X"), ("Río Negro", "Los Lagos", "X"), ("San Juan de la Costa", "Los Lagos", "X"), ("San Pablo", "Los Lagos", "X"),
    # Aysén (XI)
    ("Aysén", "Aysén", "XI"), ("Chile Chico", "Aysén", "XI"), ("Cisnes", "Aysén", "XI"), ("Cochrane", "Aysén", "XI"), ("Coyhaique", "Aysén", "XI"), ("Guaitecas", "Aysén", "XI"), ("Lago Verde", "Aysén", "XI"), ("O'Higgins", "Aysén", "XI"), ("Río Ibáñez", "Aysén", "XI"), ("Tortel", "Aysén", "XI"),
    # Magallanes (XII)
    ("Antártica", "Magallanes", "XII"), ("Cabo de Hornos", "Magallanes", "XII"), ("Laguna Blanca", "Magallanes", "XII"), ("Natales", "Magallanes", "XII"), ("Porvenir", "Magallanes", "XII"), ("Primavera", "Magallanes", "XII"), ("Punta Arenas", "Magallanes", "XII"), ("Río Verde", "Magallanes", "XII"), ("San Gregorio", "Magallanes", "XII"), ("Timaukel", "Magallanes", "XII"), ("Torres del Paine", "Magallanes", "XII"),
    # Metropolitana (RM)
    ("Alhué", "Metropolitana de Santiago", "RM"), ("Buin", "Metropolitana de Santiago", "RM"), ("Calera de Tango", "Metropolitana de Santiago", "RM"), ("Cerrillos", "Metropolitana de Santiago", "RM"), ("Cerro Navia", "Metropolitana de Santiago", "RM"), ("Colina", "Metropolitana de Santiago", "RM"), ("Conchalí", "Metropolitana de Santiago", "RM"), ("Curacaví", "Metropolitana de Santiago", "RM"), ("El Bosque", "Metropolitana de Santiago", "RM"), ("El Monte", "Metropolitana de Santiago", "RM"), ("Estación Central", "Metropolitana de Santiago", "RM"), ("Huechuraba", "Metropolitana de Santiago", "RM"), ("Independencia", "Metropolitana de Santiago", "RM"), ("Isla de Maipo", "Metropolitana de Santiago", "RM"), ("La Cisterna", "Metropolitana de Santiago", "RM"), ("La Florida", "Metropolitana de Santiago", "RM"), ("La Granja", "Metropolitana de Santiago", "RM"), ("La Pintana", "Metropolitana de Santiago", "RM"), ("La Reina", "Metropolitana de Santiago", "RM"), ("Lampa", "Metropolitana de Santiago", "RM"), ("Las Condes", "Metropolitana de Santiago", "RM"), ("Lo Barnechea", "Metropolitana de Santiago", "RM"), ("Lo Espejo", "Metropolitana de Santiago", "RM"), ("Lo Prado", "Metropolitana de Santiago", "RM"), ("Macul", "Metropolitana de Santiago", "RM"), ("Maipú", "Metropolitana de Santiago", "RM"), ("María Pinto", "Metropolitana de Santiago", "RM"), ("Melipilla", "Metropolitana de Santiago", "RM"), ("Ñuñoa", "Metropolitana de Santiago", "RM"), ("Padre Hurtado", "Metropolitana de Santiago", "RM"), ("Paine", "Metropolitana de Santiago", "RM"), ("Pedro Aguirre Cerda", "Metropolitana de Santiago", "RM"), ("Peñaflor", "Metropolitana de Santiago", "RM"), ("Peñalolén", "Metropolitana de Santiago", "RM"), ("Pirque", "Metropolitana de Santiago", "RM"), ("Providencia", "Metropolitana de Santiago", "RM"), ("Pudahuel", "Metropolitana de Santiago", "RM"), ("Puente Alto", "Metropolitana de Santiago", "RM"), ("Quilicura", "Metropolitana de Santiago", "RM"), ("Quinta Normal", "Metropolitana de Santiago", "RM"), ("Recoleta", "Metropolitana de Santiago", "RM"), ("Renca", "Metropolitana de Santiago", "RM"), ("San Bernardo", "Metropolitana de Santiago", "RM"), ("San Joaquín", "Metropolitana de Santiago", "RM"), ("San José de Maipo", "Metropolitana de Santiago", "RM"), ("San Miguel", "Metropolitana de Santiago", "RM"), ("San Pedro", "Metropolitana de Santiago", "RM"), ("San Ramón", "Metropolitana de Santiago", "RM"), ("Santiago", "Metropolitana de Santiago", "RM"), ("Talagante", "Metropolitana de Santiago", "RM"), ("Tiltil", "Metropolitana de Santiago", "RM"), ("Vitacura", "Metropolitana de Santiago", "RM"),
]

def main():
    conn = psycopg2.connect('postgresql://neondb_owner:REDACTED_DB_PASS@ep-dark-sunset-ah922o3v-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require')
    cursor = conn.cursor()
    
    # Limpiar tabla
    cursor.execute("DELETE FROM comunas_chile")
    
    # Insertar todas
    cursor.executemany(
        "INSERT INTO comunas_chile (nombre, region, region_number) VALUES (%s, %s, %s) ON CONFLICT DO NOTHING",
        COMUNAS
    )
    conn.commit()
    
    cursor.execute("SELECT COUNT(*) FROM comunas_chile")
    print(f"✅ Total comunas en DB: {cursor.fetchone()[0]}")
    
    cursor.close()
    conn.close()

if __name__ == "__main__":
    main()
